### ISSUE TITLE
onBeforeSignIn wrong type declaration

### ISSUE THREAD

**Issue by marlena-sliwinska** [bjerkio/oidc-react#930]
currentyly in code 
![image](https://user-images.githubusercontent.com/64863486/212820399-2d6eae0d-bef2-4280-9681-ba691f883b7a.png)
in documentation: 
![image](https://user-images.githubusercontent.com/64863486/212820711-51514aae-b1c1-4f12-ac0e-4d3da510d4ac.png)

**Comment by cobraz** [comment]
This should be fixed :)

**Comment by UlanTursunbek** [comment]
@simenandre   https://github.com/bjerkio/oidc-react/blob/main/src/AuthContextInterface.ts types still not changed
